const types = {
  FETCH_APPLICATIONS: "FETCH_APPLICATIONS",
  ADD_APPLICATION : "ADD_APPLICATION",
  FETCH_SUBMISSION_CENTERS: "FETCH_SUBMISSION_CENTERS",
  UPDATE_SUBMISSION_CENTER: "UPDATE_SUBMISSION_CENTER",
  RESET_APPLICATIONS: "RESET_APPLICATIONS",
  DELETE_SUBMISSION: "DELETE_SUBMISSION",
  SET_SELECTED_SUBMISSION: "SET_SELECTED_SUBMISSION",
  RETRY_UPLOADS: "RETRY_UPLOADS"
};

export default types;
