const types = {
  FETCH_CUSTOMERS: "FETCH_CUSTOMERS",
  ADD_CUSTOMER: "ADD_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  SET_SELECTED_CUSTOMER: "SET_SELECTED_CUSTOMER",
  SUBSCRIPTIONS_IN_USE: "SUBSCRIPTIONS_IN_USE",
  LICENCES_UN_ASSIGNED: "LICENCES_UN_ASSIGNED",
  RESET_IN_USE_UN_ASSIGNED: "RESET_IN_USE_UN_ASSIGNED",
  GET_LICENCE_LOOKUPS: "GET_LICENCE_LOOKUPS"
};

export default types;
