const types = {
  FETCH_CUSTOMERS: "FETCH_CUSTOMERS",
  SET_SELECTED_CUSTOMER: "SET_SELECTED_CUSTOMER",
  SUBSCRIPTIONS_IN_USE: "SUBSCRIPTIONS_IN_USE",
  LICENCES_UN_ASSIGNED: "LICENCES_UN_ASSIGNED",
  RESET_IN_USE_UN_ASSIGNED: "RESET_IN_USE_UN_ASSIGNED"
};

export default types;
