const types = {
  LOGIN: 'LOGIN',
  SET_LOGGED_STATUS: 'SET_LOGGED_STATUS',
  SET_OTP_STATUS: 'SET_OTP_STATUS',
  SEND_OTP: 'SEND_OTP',
  VERIFY_OTP: 'VERIFY_OTP',
  VERIFIED_OTP: 'VERIFIED_OTP',
  RESET_OTP: 'RESET_OTP',
  SET_OTP_ERROR: 'SET_OTP_ERROR',
  RESET_OTP_ERROR: 'RESET_OTP_ERROR',
  RESET_LOGIN_ERROR: 'RESET_LOGIN_ERROR'
};

export default types;
