const types = {
  LOGIN: "LOGIN",
  CREATE_UPDATE_PROFILE: "CREATE_UPDATE_PROFILE",
  SET_LOGGED_STATUS: "SET_LOGGED_STATUS",
  SET_OTP_STATUS: "SET_OTP_STATUS",
  SEND_OTP: "SEND_OTP",
  VERIFY_OTP: "VERIFY_OTP",
  VERIFIED_OTP: "VERIFIED_OTP",
  RESET_OTP: "RESET_OTP",
  SET_LOGIN_ERROR: "SET_LOGIN_ERROR",
  SET_OTP_ERROR: "SET_OTP_ERROR",
  RESET_OTP_ERROR: "RESET_OTP_ERROR",
  RESET_LOGIN_ERROR: "RESET_LOGIN_ERROR",
  FORGOT_PWD: "FORGOT_PWD",
  RESET_PWD: "RESET_PWD",
  FORGOT_PWD_ERROR: "FORGOT_PWD_ERROR",
  LOGOUT: "LOGOUT"
};

export default types;
