const types = {
  FETCH_SEQUENCES: "FETCH_SEQUENCES",
  SET_SELECTED_SEQUENCE: "SET_SELECTED_SEQUENCE",
  FETCH_SEQUENCE_JSON: "FETCH_SEQUENCE_JSON",
  FETCHED_SEQUENCE_JSON: "FETCHED_SEQUENCE_JSON",
  FETCH_LIFE_CYCLE_JSON: "FETCH_LIFE_CYCLE_JSON",
  FETCHED_LIFE_CYCLE_JSON: "FETCHED_LIFE_CYCLE_JSON",
  VALIDATE_SEQUENCE: "VALIDATE_SEQUENCE",
  ASSIGN_PERMISSIONS: "ASSIGN_PERMISSIONS"
};

export default types;
