const types = {
  FETCH_SEQUENCES: "FETCH_SEQUENCES",
  SET_SELECTED_SEQUENCE: "SET_SELECTED_SEQUENCE",
  FETCH_SEQUENCE_JSON: "FETCH_SEQUENCE_JSON",
  FETCHED_SEQUENCE_JSON: "FETCHED_SEQUENCE_JSON",
  FETCH_LIFE_CYCLE_JSON: "FETCH_LIFE_CYCLE_JSON",
  FETCHED_LIFE_CYCLE_JSON: "FETCHED_LIFE_CYCLE_JSON",
  VALIDATE_SEQUENCE: "VALIDATE_SEQUENCE",
  ASSIGN_PERMISSIONS: "ASSIGN_PERMISSIONS",
  FIND_TEXT: "FIND_TEXT",
  FIND_MATCH_BY: "FIND_MATCH_BY",
  FIND_SORT_BY_TITLE: "FIND_SORT_BY_TITLE",
  FIND_SELECTED_RESULT: "FIND_SELECTED_RESULT",
  FIND_SORT_BY_FILE: "FIND_SORT_BY_FILE",
  CLEAR_SEARCH_RESULTS: "CLEAR_SEARCH_RESULTS",
  RESET_FIND: "RESET_FIND"
};

export default types;
