const types = {
  FETCH_DEPARTMENTS: "FETCH_DEPARTMENTS",
  FETCH_LICENCES: "FETCH_LICENCES",
  FETCH_ALL_LICENCES: "FETCH_ALL_LICENCES",
  RESET_ALL_LICENCES: "RESET_ALL_LICENCES",
  ASSIGN_LICENSE: "ASSIGN_LICENSE",
  REVOKE_LICENSE: "REVOKE_LICENSE",
  FETCH_USERS: "FETCH_USERS",
  FETCH_CUSTOMER_ADMINS: "FETCH_CUSTOMER_ADMINS",
  FETCH_USERS_OF_FILE_OR_SUBMISSION: "FETCH_USERS_OF_FILE_OR_SUBMISSION",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
  SET_SELECTED_USER: "SET_SELECTED_USER",
  RESEND_INVITATION_MAIL: "RESEND_INVITATION_MAIL"
};

export default types;
