const types = {
  FETCH_DEPARTMENTS: "FETCH_DEPARTMENTS",
  FETCH_LICENCES: "FETCH_LICENCES",
  FETCH_ALL_LICENCES: "FETCH_ALL_LICENCES",
  FETCH_USERS: "FETCH_USERS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  ADD_CUSTOMER: "ADD_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
  SET_SELECTED_USER: "SET_SELECTED_USER"
};

export default types;
